[package]
name = "ekke_config"
version = "0.1.0"
authors = ["Naja Melan <najamelan@autistici.org>"]
edition = "2018"

[dependencies]

	failure      = "0.1.5"
	serde        = "1.0.88"
	serde_derive = "1.0.88"
	serde-hjson  = { version = "0.9.0", default-features = false }
